import type { Dict } from '@lares/shared';

/** Site builder: service messages and the validation messages of the builder spec (packages/shared/src/builder.ts). */
export const BUILDER_EN: Dict = {
  'Giao diện "{id}" không phải giao diện tự tạo': 'Template "{id}" was not made with the site builder',
  'Cảnh báo: không tìm thấy ảnh {file} của giao diện {id}': 'Warning: image {file} of template {id} was not found',
  'Đã tạo website từ trình tạo giao diện ({count} khối, {images} ảnh)': 'Website generated by the site builder ({count} sections, {images} images)',
  'Không tìm thấy tệp': 'File not found',
  'Chỉ cập nhật được giao diện tự tạo đã lưu': 'Only saved site-builder templates can be updated',
  'Chỉ xoá được giao diện tự tạo đã lưu': 'Only saved site-builder templates can be deleted',
  'Đang dựng bản xem trước…': 'Building the preview…',
  // spec validation
  'Không được chứa ký tự < >': 'Must not contain < or >',
  'Ảnh phải là ảnh có sẵn của giao diện hoặc URL https://': 'Images must be a bundled template image or an https:// URL',
  'Anchor chỉ gồm chữ thường, số và dấu gạch ngang': 'Anchors may only contain lowercase letters, digits and hyphens',
  'Ngày kết thúc không hợp lệ': 'Invalid end date',
  'Kiểu bố cục không hợp lệ': 'Invalid layout variant',
  'Nhập tên thương hiệu': 'Enter the business name',
  'Số Zalo không hợp lệ': 'Invalid Zalo number',
  'Logo quá lớn': 'Logo is too large',
  'Logo phải là ảnh PNG, JPEG hoặc WebP': 'Logo must be a PNG, JPEG or WebP image',
  'Màu phải có dạng #rrggbb': 'Colour must look like #rrggbb',
  'Mỗi loại khối chỉ dùng một lần': 'Each section type can only be used once',
  'Bật ít nhất một khối nội dung': 'Enable at least one content section',
  'Nội dung có biến không hợp lệ (chỉ dùng {brand}, {slogan}, {phone}, {email}, {address}, {city})':
    'The copy contains an unknown placeholder (only {brand}, {slogan}, {phone}, {email}, {address}, {city} are allowed)',
  'Nhập tên giao diện': 'Enter a template name',
};
