-- Lares anonymous install counter (Cloudflare D1)
-- Apply: npx wrangler d1 execute lares-telemetry --remote --file=schema.sql

-- One row per install id (random UUID generated by install.sh, stored in /etc/lares/install-id)
CREATE TABLE IF NOT EXISTS installs (
  install_id TEXT PRIMARY KEY,
  first_seen TEXT NOT NULL,      -- ISO timestamp of the first ping
  last_seen  TEXT NOT NULL,      -- ISO timestamp of the latest ping
  last_event TEXT NOT NULL,      -- install | upgrade | heartbeat
  version    TEXT NOT NULL,
  os         TEXT NOT NULL,      -- /etc/os-release ID, e.g. ubuntu
  os_version TEXT NOT NULL,      -- /etc/os-release VERSION_ID, e.g. 24.04
  arch       TEXT NOT NULL,      -- amd64 | arm64
  lang       TEXT NOT NULL       -- vi | en
);
CREATE INDEX IF NOT EXISTS idx_installs_last_seen ON installs(last_seen);

-- At most one row per (day, install, event); pruned after 400 days by the Worker's cron
CREATE TABLE IF NOT EXISTS daily (
  day        TEXT NOT NULL,      -- YYYY-MM-DD (UTC)
  install_id TEXT NOT NULL,
  event      TEXT NOT NULL,
  version    TEXT NOT NULL,
  os         TEXT NOT NULL,
  os_version TEXT NOT NULL,
  arch       TEXT NOT NULL,
  lang       TEXT NOT NULL,
  PRIMARY KEY (day, install_id, event)
);
CREATE INDEX IF NOT EXISTS idx_daily_event_day ON daily(event, day);
