import fs from 'node:fs/promises';
import path from 'node:path';
import { config } from '../config.js';
import { localExecutor } from '../executors/index.js';
import { t } from '../i18n/index.js';
import { ngxPath, shq } from '../lib/shell.js';

/**
 * Developer preview (dry-run only): run an unprivileged nginx that serves the *port-based* sites
 * Lares generated, so http://localhost:8001 works on a laptop. Domain sites (port 80/443) and the
 * real system nginx are never touched.
 */
const prefix = () => path.join(config.dataDir, 'nginx-dev');
const confFile = () => path.join(prefix(), 'nginx.conf');
const pidFile = () => path.join(prefix(), 'nginx.pid');

let nginxBin: string | null | undefined;
let missingWarned = false;

async function findNginx(): Promise<string | null> {
  if (nginxBin !== undefined) return nginxBin;
  const r = await localExecutor.exec('command -v nginx');
  nginxBin = r.code === 0 ? r.stdout.trim() : null;
  return nginxBin;
}

/** Directory of the stock nginx.conf (`nginx -V` -> --conf-path): holds mime.types and fastcgi_params. */
async function stockConfDir(bin: string): Promise<string | null> {
  const r = await localExecutor.exec(`${shq(bin)} -V 2>&1`);
  const conf = r.stdout.match(/--conf-path=(\S+)/)?.[1];
  for (const d of [conf && path.dirname(conf), '/opt/homebrew/etc/nginx', '/usr/local/etc/nginx']) {
    if (d && (await fs.access(path.join(d, 'mime.types')).then(() => true, () => false))) return d;
  }
  return null;
}

async function running(bin: string): Promise<boolean> {
  const pid = Number((await fs.readFile(pidFile(), 'utf8').catch(() => '')).trim());
  if (!pid) return false;
  try {
    process.kill(pid, 0);
    return true;
  } catch {
    return false;
  }
}

export async function syncDevNginx(log?: (msg: string) => void) {
  if (!config.dryRun) return;
  const bin = await findNginx();
  if (!bin) {
    if (!missingWarned) log?.(`[dev] ${t('Không có nginx trên máy - cài bằng "brew install nginx" để xem trực tiếp các site chạy theo port (http://localhost:8001)')}`);
    missingWarned = true;
    return;
  }
  const tmp = path.join(prefix(), 'tmp');
  await fs.mkdir(tmp, { recursive: true });
  const stock = await stockConfDir(bin);
  const mime = stock ? path.join(stock, 'mime.types') : null;
  // vhosts use `include fastcgi_params;`, which nginx resolves next to *our* nginx.conf
  if (stock) await fs.copyFile(path.join(stock, 'fastcgi_params'), path.join(prefix(), 'fastcgi_params')).catch(() => {});
  await fs.writeFile(
    confFile(),
    `# Generated by Lares (dev preview of port-based sites)
pid ${ngxPath(pidFile())};
error_log ${ngxPath(path.join(prefix(), 'error.log'))};
events {}
http {
${mime ? `    include ${ngxPath(mime)};\n` : ''}    default_type application/octet-stream;
    client_body_temp_path ${ngxPath(`${tmp}/body`)};
    proxy_temp_path ${ngxPath(`${tmp}/proxy`)};
    fastcgi_temp_path ${ngxPath(`${tmp}/fastcgi`)};
    uwsgi_temp_path ${ngxPath(`${tmp}/uwsgi`)};
    scgi_temp_path ${ngxPath(`${tmp}/scgi`)};
    include ${ngxPath(config.nginxGlobalConf)};
    include ${ngxPath(path.join(config.nginxEnabled, 'site*.localhost.conf'))};
}
`,
  );
  const args = `-p ${shq(prefix())} -c ${shq(confFile())}`;
  const test = await localExecutor.exec(`${shq(bin)} -t ${args} 2>&1`);
  if (test.code !== 0) {
    log?.(`[dev] ${t('nginx dev báo lỗi cấu hình: {error}', { error: test.stdout.trim().split('\n').slice(-2).join(' ') })}`);
    return;
  }
  const r = (await running(bin)) ? await localExecutor.exec(`${shq(bin)} ${args} -s reload 2>&1`) : await localExecutor.exec(`${shq(bin)} ${args} 2>&1`);
  if (r.code !== 0) log?.(`[dev] ${t('Không chạy được nginx dev: {error}', { error: r.stdout.trim() })}`);
}

export async function stopDevNginx() {
  if (!config.dryRun || !nginxBin) return;
  if (await running(nginxBin)) await localExecutor.exec(`${shq(nginxBin)} -p ${shq(prefix())} -c ${shq(confFile())} -s quit 2>&1`);
}
