import crypto from 'node:crypto';
import path from 'node:path';
import type { WordpressConfig } from '@tpanel/shared';
import { config } from '../config.js';
import { shq } from '../lib/shell.js';
import { host, type HostLogger } from './host.js';

const phpStr = (v: string) => `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

function salt(): string {
  // Printable ASCII without quote/backslash so the value is trivially safe inside a PHP string.
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#%&()*+,-./:;<=>?@[]^_{|}~';
  return Array.from(crypto.randomBytes(64), (b) => chars[b % chars.length]).join('');
}

export function renderWpConfig(db: { name: string; user: string; password: string; host: string }, prefix = 'wp_'): string {
  const keys = ['AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY', 'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT'];
  return `<?php
// Generated by TPanel
define( 'DB_NAME', ${phpStr(db.name)} );
define( 'DB_USER', ${phpStr(db.user)} );
define( 'DB_PASSWORD', ${phpStr(db.password)} );
define( 'DB_HOST', ${phpStr(db.host)} );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

${keys.map((k) => `define( '${k}', ${phpStr(salt())} );`).join('\n')}

$table_prefix = ${phpStr(prefix)};

define( 'WP_DEBUG', false );
define( 'FS_METHOD', 'direct' );

// Behind a TLS-terminating proxy / load balancer
if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' ) {
	$_SERVER['HTTPS'] = 'on';
}

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
`;
}

/** wp-cli as root - only for WordPress code TPanel downloaded itself (fresh installs). */
export const wpCli = (webRoot: string, args: string) => `wp --path=${shq(webRoot)} --allow-root --skip-plugins --skip-themes ${args}`;

/** wp-cli as the web user - for migrated sites, whose wp-config.php/plugins are untrusted PHP. */
export const wpCliAsWebUser = (webRoot: string, home: string, args: string) =>
  host.asWebUser(`wp --path=${shq(webRoot)} --skip-plugins --skip-themes ${args}`, { cwd: webRoot, home });

/**
 * Download WordPress, write wp-config.php and - when wp-cli is present and admin credentials are
 * given - run `wp core install`. Returns true when the site is fully installed (not just downloaded).
 */
export async function installWordpress(
  webRoot: string,
  siteUrl: string,
  db: { name: string; user: string; password: string },
  wp: WordpressConfig,
  log: HostLogger,
): Promise<boolean> {
  const hasCli = config.dryRun || (await host.has('wp'));
  log('Đang tải WordPress...');
  if (hasCli) {
    await host.mutate(wpCli(webRoot, `core download --locale=${shq(wp.locale)} --force`), { log, timeoutMs: 10 * 60_000 });
  } else {
    const url = wp.locale === 'en_US' ? 'https://wordpress.org/latest.tar.gz' : `https://${wp.locale.split('_')[0]}.wordpress.org/latest-${wp.locale}.tar.gz`;
    await host.mutate(`curl -fsSL ${shq(url)} | tar -xz --strip-components=1 -C ${shq(webRoot)}`, { log, timeoutMs: 10 * 60_000 });
  }
  await host.writeFile(path.join(webRoot, 'wp-config.php'), renderWpConfig({ ...db, host: 'localhost' }), 0o640);

  if (hasCli && wp.adminUser && wp.adminPassword && wp.adminEmail) {
    log('Đang chạy wp core install...');
    await host.mutate(
      wpCli(
        webRoot,
        `core install --url=${shq(siteUrl)} --title=${shq(wp.title || siteUrl)} --admin_user=${shq(wp.adminUser)} --admin_password=${shq(wp.adminPassword)} --admin_email=${shq(wp.adminEmail)} --skip-email`,
      ),
      { log },
    );
    return true;
  }
  log(`Hoàn tất cài WordPress tại ${siteUrl}/wp-admin/install.php`);
  return false;
}

/** Update DB credentials in an existing wp-config.php (migrated sites). */
export function rewriteWpConfig(src: string, db: { name: string; user: string; password: string; host: string }): string {
  const set = (text: string, key: string, value: string) => {
    const re = new RegExp(`define\\s*\\(\\s*(['"])${key}\\1\\s*,\\s*(['"])(?:\\\\.|(?!\\2).)*\\2\\s*\\)`, 'i');
    const replacement = `define( '${key}', ${phpStr(value)} )`;
    return re.test(text) ? text.replace(re, () => replacement) : text.replace(/<\?php/, () => `<?php\n${replacement};`);
  };
  let out = set(src, 'DB_NAME', db.name);
  out = set(out, 'DB_USER', db.user);
  out = set(out, 'DB_PASSWORD', db.password);
  out = set(out, 'DB_HOST', db.host);
  return out;
}

export async function hasWpCli() {
  return host.has('wp');
}
