import crypto from 'node:crypto';
import fs from 'node:fs/promises';
import path from 'node:path';
import { DB_IDENT_RE, type WordpressConfig } from '@tpanel/shared';
import { config } from '../config.js';
import { shq } from '../lib/shell.js';
import { parseWpConfig } from '../migration/appDetect.js';
import { host, type HostLogger } from './host.js';
import * as mysql from './mysql.js';

const phpStr = (v: string) => `'${v.replace(/\\/g, '\\\\').replace(/'/g, "\\'")}'`;

function salt(): string {
  // Printable ASCII without quote/backslash so the value is trivially safe inside a PHP string.
  const chars = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789!#%&()*+,-./:;<=>?@[]^_{|}~';
  return Array.from(crypto.randomBytes(64), (b) => chars[b % chars.length]).join('');
}

const PORT_HOST_FIX_MARKER = 'TPANEL_PORT_HOST_FIX';

/**
 * Sites served on a custom port (http://IP:8001): when the Host header reaches PHP without the port
 * (seen with some FastCGI setups), WordPress builds its current URL without ":8001", decides it differs
 * from the stored home URL and redirects to itself forever. Restore the port from the real server port.
 */
export const PORT_HOST_FIX = `// ${PORT_HOST_FIX_MARKER}: keep the port in HTTP_HOST for sites served on a custom port (prevents redirect loops)
if ( isset( $_SERVER['HTTP_HOST'], $_SERVER['SERVER_PORT'] ) && strpos( $_SERVER['HTTP_HOST'], ':' ) === false
	&& ! in_array( (string) $_SERVER['SERVER_PORT'], array( '80', '443' ), true ) ) {
	$_SERVER['HTTP_HOST'] .= ':' . $_SERVER['SERVER_PORT'];
}
`;

/** Insert PORT_HOST_FIX into an existing wp-config.php (idempotent). */
export function addPortHostFix(src: string): string {
  if (src.includes(PORT_HOST_FIX_MARKER)) return src;
  return /<\?php[^\n]*\n/.test(src) ? src.replace(/<\?php[^\n]*\n/, (m) => `${m}${PORT_HOST_FIX}\n`) : src;
}

export function renderWpConfig(db: { name: string; user: string; password: string; host: string }, prefix = 'wp_'): string {
  const keys = ['AUTH_KEY', 'SECURE_AUTH_KEY', 'LOGGED_IN_KEY', 'NONCE_KEY', 'AUTH_SALT', 'SECURE_AUTH_SALT', 'LOGGED_IN_SALT', 'NONCE_SALT'];
  return `<?php
// Generated by TPanel
define( 'DB_NAME', ${phpStr(db.name)} );
define( 'DB_USER', ${phpStr(db.user)} );
define( 'DB_PASSWORD', ${phpStr(db.password)} );
define( 'DB_HOST', ${phpStr(db.host)} );
define( 'DB_CHARSET', 'utf8mb4' );
define( 'DB_COLLATE', '' );

${keys.map((k) => `define( '${k}', ${phpStr(salt())} );`).join('\n')}

$table_prefix = ${phpStr(prefix)};

define( 'WP_DEBUG', false );
define( 'FS_METHOD', 'direct' );

${PORT_HOST_FIX}
// Behind a TLS-terminating proxy / load balancer
if ( isset( $_SERVER['HTTP_X_FORWARDED_PROTO'] ) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https' ) {
	$_SERVER['HTTPS'] = 'on';
}

if ( ! defined( 'ABSPATH' ) ) {
	define( 'ABSPATH', __DIR__ . '/' );
}
require_once ABSPATH . 'wp-settings.php';
`;
}

/** wp-cli as root - only for WordPress code TPanel downloaded itself (fresh installs). */
export const wpCli = (webRoot: string, args: string) => `wp --path=${shq(webRoot)} --allow-root --skip-plugins --skip-themes ${args}`;

/** wp-cli as the web user - for migrated sites, whose wp-config.php/plugins are untrusted PHP. */
export const wpCliAsWebUser = (webRoot: string, home: string, args: string) =>
  host.asWebUser(`wp --path=${shq(webRoot)} --skip-plugins --skip-themes ${args}`, { cwd: webRoot, home });

/**
 * Download WordPress, write wp-config.php and - when wp-cli is present and admin credentials are
 * given - run `wp core install`. Returns true when the site is fully installed (not just downloaded).
 */
export async function installWordpress(
  webRoot: string,
  siteUrl: string,
  db: { name: string; user: string; password: string },
  wp: WordpressConfig,
  log: HostLogger,
): Promise<boolean> {
  const hasCli = config.dryRun || (await host.has('wp'));
  log('Đang tải WordPress...');
  if (hasCli) {
    await host.mutate(wpCli(webRoot, `core download --locale=${shq(wp.locale)} --force`), { log, timeoutMs: 10 * 60_000 });
  } else {
    const url = wp.locale === 'en_US' ? 'https://wordpress.org/latest.tar.gz' : `https://${wp.locale.split('_')[0]}.wordpress.org/latest-${wp.locale}.tar.gz`;
    await host.mutate(`curl -fsSL ${shq(url)} | tar -xz --strip-components=1 -C ${shq(webRoot)}`, { log, timeoutMs: 10 * 60_000 });
  }
  await host.writeFile(path.join(webRoot, 'wp-config.php'), renderWpConfig({ ...db, host: 'localhost' }), 0o640);

  if (hasCli && wp.adminUser && wp.adminPassword && wp.adminEmail) {
    log('Đang chạy wp core install...');
    await host.mutate(
      wpCli(
        webRoot,
        `core install --url=${shq(siteUrl)} --title=${shq(wp.title || siteUrl)} --admin_user=${shq(wp.adminUser)} --admin_password=${shq(wp.adminPassword)} --admin_email=${shq(wp.adminEmail)} --skip-email`,
      ),
      { log },
    );
    return true;
  }
  log(`Hoàn tất cài WordPress tại ${siteUrl}/wp-admin/install.php`);
  return false;
}

/** Update DB credentials in an existing wp-config.php (migrated sites). */
export function rewriteWpConfig(src: string, db: { name: string; user: string; password: string; host: string }): string {
  const set = (text: string, key: string, value: string) => {
    const re = new RegExp(`define\\s*\\(\\s*(['"])${key}\\1\\s*,\\s*(['"])(?:\\\\.|(?!\\2).)*\\2\\s*\\)`, 'i');
    const replacement = `define( '${key}', ${phpStr(value)} )`;
    return re.test(text) ? text.replace(re, () => replacement) : text.replace(/<\?php/, () => `<?php\n${replacement};`);
  };
  let out = set(src, 'DB_NAME', db.name);
  out = set(out, 'DB_USER', db.user);
  out = set(out, 'DB_PASSWORD', db.password);
  out = set(out, 'DB_HOST', db.host);
  return out;
}

export async function hasWpCli() {
  return host.has('wp');
}

/** Current home URL of a WordPress install (read via wp-cli as the web user), or null. */
export async function wordpressHomeUrl(webRoot: string, home: string): Promise<string | null> {
  if (config.dryRun || !(await host.has('wp'))) return null;
  const r = await host.exec(wpCliAsWebUser(webRoot, home, 'option get home'));
  const url = r.stdout.trim().split('\n').pop()?.trim() ?? '';
  return r.code === 0 && /^https?:\/\//.test(url) ? url.replace(/\/+$/, '') : null;
}

/** Search/replace pairs that move every stored form of a URL: http, https, protocol-relative, JSON-escaped. */
export function urlReplacePairs(from: string, to: string): Array<[string, string]> {
  const strip = (u: string) => u.replace(/^https?:/, '').replace(/\/+$/, '');
  const pairs: Array<[string, string]> = [];
  if (strip(from) !== strip(to)) {
    pairs.push([strip(from), strip(to)]);
    pairs.push([strip(from).replace(/\//g, '\\/'), strip(to).replace(/\//g, '\\/')]);
  }
  // going https: links that were written as http:// would be blocked as mixed content
  if (to.startsWith('https://')) pairs.push([`http:${strip(to)}`, `https:${strip(to)}`]);
  return pairs;
}

/** DB name + table prefix from the site's own wp-config.php. */
async function wpDbInfo(webRoot: string): Promise<{ name: string; prefix: string } | null> {
  const src = await fs.readFile(path.join(webRoot, 'wp-config.php'), 'utf8').catch(() => null);
  const c = src ? parseWpConfig(src) : null;
  if (!c) return null;
  const prefix = c.prefix ?? 'wp_';
  return DB_IDENT_RE.test(c.name) && /^[A-Za-z0-9_]+$/.test(prefix) ? { name: c.name, prefix } : null;
}

/**
 * Fallback without (working) wp-cli: update what keeps the site reachable - home/siteurl and post
 * content. Serialized data (widgets, page-builder meta) is left alone; only wp-cli handles it safely.
 */
async function replaceUrlViaSql(webRoot: string, to: string, from: string | null | undefined, log: HostLogger): Promise<boolean> {
  const info = await wpDbInfo(webRoot);
  if (!info) return false;
  const t = (table: string) => `\`${info.name}\`.\`${info.prefix}${table}\``;
  const rows = await mysql.query<Array<{ option_value: string }>>(`SELECT option_value FROM ${t('options')} WHERE option_name = 'home'`);
  const current = (from ?? rows[0]?.option_value ?? '').replace(/\/+$/, '');
  await mysql.query(`UPDATE ${t('options')} SET option_value = ? WHERE option_name IN ('home', 'siteurl')`, [to]);
  for (const [a, b] of current ? urlReplacePairs(current, to) : []) {
    await mysql.query(`UPDATE ${t('posts')} SET post_content = REPLACE(post_content, ?, ?), post_excerpt = REPLACE(post_excerpt, ?, ?)`, [a, b, a, b]);
  }
  log(`Đã đổi URL WordPress qua database: ${current || '?'} → ${to} (widget/page-builder có thể còn link cũ - nên chạy wp search-replace khi có wp-cli)`);
  return true;
}

/**
 * Move a WordPress site to a new base URL (domain assigned, or http -> https after SSL).
 * wp-cli runs as the web user: by now the site may contain third-party plugins/themes.
 * Never throws: a failure here must not leave the caller half-way (the domain is already switched).
 */
export async function wordpressReplaceUrl(webRoot: string, home: string, to: string, log: HostLogger, from?: string | null): Promise<boolean> {
  if (config.dryRun) {
    log(`[dry-run] wp search-replace ${from ?? '<home>'} ${to}`);
    return true;
  }
  const msg = (e: unknown) => (e instanceof Error ? e.message : String(e)).split('\n').slice(-2).join(' ');
  if (await host.has('wp')) {
    try {
      const current = from ?? (await wordpressHomeUrl(webRoot, home));
      if (!current) throw new Error('không đọc được URL hiện tại (option home)');
      if (current === to) return true;
      const run = (args: string) => host.run(wpCliAsWebUser(webRoot, home, args), { timeoutMs: 30 * 60_000 });
      // serialized PHP data needs wp-cli's search-replace; a plain SQL REPLACE would corrupt it
      for (const [a, b] of urlReplacePairs(current, to)) {
        await run(`search-replace ${shq(a)} ${shq(b)} --all-tables-with-prefix --skip-columns=guid --precise --report-changed-only`);
      }
      await run(`option update home ${shq(to)}`);
      await run(`option update siteurl ${shq(to)}`);
      await run('cache flush').catch(() => undefined);
      log(`Đã đổi URL WordPress: ${current} → ${to}`);
      return true;
    } catch (err) {
      log(`Cảnh báo: wp-cli không đổi được URL (${msg(err)}) - chuyển sang cập nhật trực tiếp trong database`);
    }
  }
  try {
    if (await replaceUrlViaSql(webRoot, to, from, log)) return true;
  } catch (err) {
    log(`Cảnh báo: không cập nhật được database (${msg(err)})`);
  }
  log(
    `CẦN LÀM TAY: WordPress vẫn giữ URL cũ. Chạy trên VPS: sudo -u ${config.webUser} wp --path=${shq(webRoot)} option update home ${shq(to)} && sudo -u ${config.webUser} wp --path=${shq(webRoot)} option update siteurl ${shq(to)}`,
  );
  return false;
}

/** Patch wp-config.php of a port-based site that was created before PORT_HOST_FIX existed. */
export async function ensurePortHostFix(webRoot: string, log?: HostLogger): Promise<boolean> {
  const file = path.join(webRoot, 'wp-config.php');
  const src = await fs.readFile(file, 'utf8').catch(() => null);
  if (src === null) return false;
  const next = addPortHostFix(src);
  if (next === src) return false;
  await host.writeFile(file, next, 0o640);
  await host.mutate(`chown ${shq(`${config.webUser}:${config.webUser}`)} ${shq(file)}`, { log });
  log?.(`Đã vá wp-config.php (giữ port trong HTTP_HOST): ${file}`);
  return true;
}
